repository_type: pipeline

nf_core_version: 3.5.1

lint: {}

template:
  org: nf-core
  name: StarCaller
  description: A pharmaocogenomics pipeline to call star alleles for a set of supported
    pharmacogenes from raw sequencing data
  author: Sven van der Maas
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
